In [1]:
import numpy as np
import gd

In [2]:
n = 10
A = np.eye(n) * np.arange(1,11)
b=np.ones(n)
x0=np.zeros(n)

In [3]:
func = lambda x: 0.5 * x.T @ A @ x - b.T @ x
grad = lambda x: A @ x - b

In [5]:
k=100
xk=x0
xk_k = x0

for i in range(k):
    y = xk
    xk = gd.fast_grad_des_v1(xk, xk_k, grad, 0.1)
    xk_k = y
    print(xk)
    print(func(xk))

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
-0.725
[0.27 0.26 0.25 0.24 0.23 0.22 0.21 0.2  0.19 0.18]
-1.0207499999999998
[0.479 0.436 0.395 0.356 0.319 0.284 0.251 0.22  0.191 0.164]
-1.0935554999999995
[0.6983 0.5896 0.4925 0.4064 0.3307 0.2648 0.2081 0.16   0.1199 0.0872]
-1.231459875
[0.90391 0.69456 0.52275 0.38416 0.27471 0.19056 0.12811 0.084   0.05511
 0.03856]
-1.27605933155
[1.078007 0.739616 0.490125 0.312704 0.192563 0.116832 0.074441 0.056
 0.053679 0.061088]
-1.2938575536675003
[1.2094839 0.7277376 0.4169875 0.2304576 0.1305639 0.0877504 0.0793971
 0.0888    0.1042231 0.1180224]
-1.327505943478755
[1.29371703 0.67268736 0.33338125 0.17247744 0.11568267 0.11183488
 0.12778401 0.144      0.15085759 0.14554752]
-1.3329946507409345
[1.33173183 0.5941097  0.26648187 0.15710234 0.14593635 0.16400154
 0.17704473 0.17296    0.15239335 0.1220201 ]
-1.3459275122900227
[1.32897049 0.51242563 0.23301781 0.18196132 0.19717112 0.20733394
 0.192522   0.15776    0.11646794 0.08117806]
-1.